- name: Install Docker Compose if not present
  apt:
    name: docker-compose
    state: present
  become: true

- name: Create directory for Prometheus Docker Compose
  file:
    path: /opt/prometheus
    state: directory

- name: Copy Docker Compose file for Prometheus
  template:
    src: docker-compose.yml.j2
    dest: /opt/prometheus/docker-compose.yml

- name: Start Prometheus service using Docker Compose
  command: docker-compose up -d
  args:
    chdir: /opt/prometheus
  become: true
