    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install Certbot
      apt:
        name: certbot
        state: present

    - name: Install python3-certbot-dns-cloudflare plugin
      apt:
        name: python3-certbot-dns-cloudflare
        state: present

    - name: Create Cloudflare credentials file for Certbot
      copy:
        dest: /etc/letsencrypt/cloudflare.ini
        content: |
          dns_cloudflare_email = iyaron08@gmail.com
          dns_cloudflare_api_key = 38dad959d491aaaf06240a6820c0e6e822132
        mode: '0600'

    - name: Obtain SSL certificate for *.imron.studentdumbways.my.id using Cloudflare DNS challenge
      community.letsencrypt.acme_certificate:
        account_email: "iyaron@gmail.com"
        cert_name: "*.imron.studentdumbways.my.id"
        domain: "*.imron.studentdumbways.my.id"
        challenge: dns-01
        dns_plugin: cloudflare
        dns_cloudflare_credentials: /etc/letsencrypt/cloudflare.ini
        state: present
      register: certbot_result

    - name: Ensure Nginx is restarted if certificate is obtained
      service:
        name: nginx
        state: restarted
      when: certbot_result.changed

