cadvisor_container_name: "cadvisor"
cadvisor_image: "gcr.io/cadvisor/cadvisor:latest"
cadvisor_ports:
  - "8080:8080"
cadvisor_volumes:
  - "/:/rootfs:ro"
  - "/var/run:/var/run:rw"
  - "/sys:/sys:ro"
  - "/var/lib/docker/:/var/lib/docker:ro"
cadvisor_restart_policy: "always"
