---
- name: Pull SonarQube Docker image
  docker_image:
    name: sonarqube
    tag: latest
    source: pull

- name: Create a Docker volume for SonarQube data
  docker_volume:
    name: sonarqube_data

- name: Create a Docker volume for SonarQube extensions
  docker_volume:
    name: sonarqube_extensions

- name: Run SonarQube container
  docker_container:
    name: sonarqube
    image: sonarqube:latest
    state: started
    restart_policy: always
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
    env:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://localhost:5432/sonarqube
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar_password
    networks:
      - bridge
