
    # Membuat direktori untuk konfigurasi Prometheus
    - name: Create Prometheus config directory
      file:
        path: /etc/prometheus
        state: directory
        mode: '0755'

    # Menyalin konfigurasi Prometheus ke file prometheus.yml
    - name: Create Prometheus configuration file
      copy:
        dest: /etc/prometheus/prometheus.yml
        content: |
          global:
            scrape_interval: 15s  

          scrape_configs:
            - job_name: 'prometheus'
              static_configs:
                - targets: ['localhost:9090'] 

    # Install Prometheus
    - name: Install Prometheus
      community.docker.docker_container:
        name: prometheus
        image: prom/prometheus
        ports:
          - 3100:9090
        volumes:
          - /etc/prometheus:/etc/prometheus
        restart_policy: unless-stopped
        command:
          - '--config.file=/etc/prometheus/prometheus.yml'
