    # Create Nginx configuration file for appserver
    - name: Create Nginx configuration file for appserver
      ansible.builtin.copy:
        dest: /etc/nginx/sites-available/default
        content: |
          server {
              listen 80;
              server_name appserver.studentdumbways.my.id;

              location / {
                  proxy_pass http://103.196.153.72:9100;  
              }
          }
      notify: Restart Nginx
      
      handlers:
    - name: Restart Nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
